In [1]:
rand(3,3)

ans =

   0.438023   0.225912   0.655421
   0.844955   0.979702   0.766646
   0.077821   0.630551   0.521290



In [2]:
a = ((1,-2,0),(-1,0,2))

parse error:

  syntax error

>>> a = ((1,-2,0),(-1,0,2))
           ^



In [3]:
a = [(1,-2,0)(-1,0,2)]

parse error:

  syntax error

>>> a = [(1,-2,0)(-1,0,2)]
           ^



In [4]:
A = [1 2; 3 4]

A =

   1   2
   3   4



In [5]:
A = [1 -2 0; -1 0 2]

A =

   1  -2   0
  -1   0   2



In [6]:
B = [2 4 ; 1 0; 1 3]

B =

   2   4
   1   0
   1   3



In [7]:
C= [1 -1;1 1]

C =

   1  -1
   1   1



In [8]:
D = [1 1; -1 1]

D =

   1   1
  -1   1



In [9]:
A*B

ans =

   0   4
   0   2



In [10]:
B*A

ans =

  -2  -4   8
   1  -2   0
  -2  -2   6



In [11]:
A*C

error: operator *: nonconformant arguments (op1 is 2x3, op2 is 2x2)


In [12]:
transpose(A) * A

ans =

   2  -2  -2
  -2   4   0
  -2   0   4



In [13]:
transpose(A) * C

ans =

   0  -2
  -2   2
   2   2



In [14]:
transpose(C) * A

ans =

   0  -2   2
  -2   2   2



In [15]:
(A*B)*C

ans =

   4   4
   2   2



In [16]:
A*(B*C)

ans =

   4   4
   2   2



In [17]:
transpose(A*B*C)

ans =

   4   2
   4   2



In [19]:
transpose(C)*transpose(B)*transpose(A)

ans =

   4   2
   4   2



In [20]:
C*B*A

error: operator *: nonconformant arguments (op1 is 2x2, op2 is 3x2)


In [21]:
transpose(A)*(C+D)

ans =

   2  -2
  -4   0
   0   4



In [22]:
(C+D)*A

ans =

   2  -4   0
  -2   0   4



In [1]:
"Aufgaben3"

ans = Aufgaben3


In [7]:
A=[4 -1 0;8 -1 -3; -16 7 -4]

A =

    4   -1    0
    8   -1   -3
  -16    7   -4



In [4]:
B=[1 0 0;2 1 0;-4 3 1]

B =

   1   0   0
   2   1   0
  -4   3   1



In [5]:
C = [4 -1 0; 0 1 -3; 0 0 5]

C =

   4  -1   0
   0   1  -3
   0   0   5



In [6]:
A = B*C

A =

    4   -1    0
    8   -1   -3
  -16    7   -4



In [8]:
A == B*C

ans =

  1  1  1
  1  1  1
  1  1  1



In [9]:
det(A)

ans =  20.000


In [10]:
det(B)

ans =  1


In [11]:
det(C)

ans =  20


In [12]:
A*A

ans =

    8   -3    3
   72  -28   15
   56  -19   -5



In [13]:
B*B

ans =

   1   0   0
   4   1   0
  -2   6   1



In [14]:
det(A*A)

ans =  400.00


In [15]:
det(C*C)

ans =  400


In [19]:
det(inverse(A))

ans =  0.050000


In [21]:
inverse(C)

ans =

   0.25000   0.25000   0.15000
   0.00000   1.00000   0.60000
   0.00000   0.00000   0.20000



In [22]:
det(A*B*C)

ans =  400.00


In [23]:
det(transpose(C)*C)

ans =  400


In [24]:
5/20

ans =  0.25000


In [25]:
inverse(C)

ans =

   0.25000   0.25000   0.15000
   0.00000   1.00000   0.60000
   0.00000   0.00000   0.20000



In [26]:
4/20

ans =  0.20000
