In [15]:
A = [1 2 3 4; 5 6 7 8; 9 0 1 2; 3 4 5 6]

A =

   1   2   3   4
   5   6   7   8
   9   0   1   2
   3   4   5   6



In [16]:
csvwrite("matrix.csv", A)

In [17]:
b = [1 2 3 4]

b =

   1   2   3   4



In [18]:
csvwrite("vector.csv", b)

In [19]:
B = csvread("matrix.csv")

B =

   1   2   3   4
   5   6   7   8
   9   0   1   2
   3   4   5   6



In [58]:
c = csvread("vector.csv")

c =

   1   2   3   4



In [60]:
x = B\transpose(c)

x =

   0.166667
  -0.680556
   0.027778
   0.736111



In [12]:
function kreuzprodukt(A, B)
    if rows(A) == columns(B)
        C = zeros(columns(A),rows(B))
        for i = [1:columns(A)]
            for k = [1:rows(B)]
            elem = 0
                for j = [1:rows(A)]
                A(i,j)
                elem = elem + A(i,j)*B(j,k)
                endfor
                C(i,k) = elem
            endfor
        endfor
    else
        printf("ERROR - Dimensions dont match")
    endif
endfunction

In [20]:
kreuzprodukt(A,B)

C =

   0   0   0   0
   0   0   0   0
   0   0   0   0
   0   0   0   0

elem = 0
ans =  1
elem =  1
ans =  2
elem =  11
ans =  3
elem =  38
ans =  4
elem =  50
C =

   50    0    0    0
    0    0    0    0
    0    0    0    0
    0    0    0    0

elem = 0
ans =  1
elem =  2
ans =  2
elem =  14
ans =  3
elem =  14
ans =  4
elem =  30
C =

   50   30    0    0
    0    0    0    0
    0    0    0    0
    0    0    0    0

elem = 0
ans =  1
elem =  3
ans =  2
elem =  17
ans =  3
elem =  20
ans =  4
elem =  40
C =

   50   30   40    0
    0    0    0    0
    0    0    0    0
    0    0    0    0

elem = 0
ans =  1
elem =  4
ans =  2
elem =  20
ans =  3
elem =  26
ans =  4
elem =  50
C =

   50   30   40   50
    0    0    0    0
    0    0    0    0
    0    0    0    0

elem = 0
ans =  5
elem =  5
ans =  6
elem =  35
ans =  7
elem =  98
ans =  8
elem =  122
C =

    50    30    40    50
   122     0     0     0
     0     0     0     0
     0     0     0     0

elem = 0
ans =  5
e

In [21]:
A*B

ans =

    50    30    40    50
   122    78   104   130
    24    26    38    50
    86    54    72    90



In [25]:
C = [ 1 0 0; 2 1 0; -4 3 1]

C =

   1   0   0
   2   1   0
  -4   3   1



In [26]:
eig(C)

ans =

   1
   1
   1



In [33]:
(C)

error: 'defi' undefined near line 1 column 1
